export const SUPPORTED_ASSETS_LIST = [
  {
    id: 'AVAX',
    name: 'Avalanche (C-Chain)',
    type: 'BASE_ASSET',
    contractAddress: '',
    nativeAsset: 'AVAX',
    decimals: 18,
    cmcID: 5805,
  },
  {
    id: 'BNB_BSC',
    name: 'BNB Smart Chain',
    type: 'BASE_ASSET',
    contractAddress: '',
    nativeAsset: 'BNB_BSC',
    decimals: 18,
    cmcID: 1839,
  },
  {
    id: 'BTC',
    name: 'Bitcoin',
    type: 'BASE_ASSET',
    contractAddress: '',
    nativeAsset: 'BTC',
    decimals: 8,
    cmcID: 1,
  },
  {
    id: 'ETH',
    name: 'Ethereum',
    type: 'BASE_ASSET',
    contractAddress: '',
    nativeAsset: 'ETH',
    decimals: 18,
    cmcID: 1027,
  },
  {
    id: 'MATIC',
    name: 'Matic Token (Ethereum)',
    type: 'ERC20',
    contractAddress: '0x7D1AfA7B718fb893dB30A3aBc0Cfc608AaCfeBB0',
    nativeAsset: 'ETH',
    decimals: 18,
    cmcID: 3890,
  },
  {
    id: 'SOL',
    name: 'Solana',
    type: 'BASE_ASSET',
    contractAddress: '',
    nativeAsset: 'SOL',
    decimals: 9,
    cmcID: 5426,
  },
  {
    id: 'USDT_ERC20',
    name: 'Tether USD (Ethereum)',
    type: 'ERC20',
    contractAddress: '0xdAC17F958D2ee523a2206206994597C13D831ec7',
    nativeAsset: 'ETH',
    decimals: 6,
    cmcID: 825,
  },
];

export const SUPPORTED_ASSETS_LIST_STAGING = [
  {
    id: 'AVAXTEST',
    name: 'Avalanche Fuji',
    type: 'BASE_ASSET',
    contractAddress: '',
    nativeAsset: 'AVAXTEST',
    decimals: 18,
  },
  {
    id: 'BNB_BSC',
    name: 'BNB Smart Chain',
    type: 'BASE_ASSET',
    contractAddress: '',
    nativeAsset: 'BNB_BSC',
    decimals: 18,
  },
  {
    id: 'BNB_TEST',
    name: 'BNB Smart Chain Testnet',
    type: 'BASE_ASSET',
    contractAddress: '',
    nativeAsset: 'BNB_TEST',
    decimals: 18,
  },
  {
    id: 'BTC',
    name: 'Bitcoin',
    type: 'BASE_ASSET',
    contractAddress: '',
    nativeAsset: 'BTC',
    decimals: 8,
  },
  {
    id: 'BTC_TEST',
    name: 'Bitcoin Test',
    type: 'BASE_ASSET',
    contractAddress: '',
    nativeAsset: 'BTC_TEST',
    decimals: 8,
  },
  {
    id: 'ETH',
    name: 'Ethereum',
    type: 'BASE_ASSET',
    contractAddress: '',
    nativeAsset: 'ETH',
    decimals: 18,
  },
  {
    id: 'ETH_TEST5',
    name: 'Ethereum Test (Sepolia)',
    type: 'BASE_ASSET',
    contractAddress: '',
    nativeAsset: 'ETH_TEST5',
    decimals: 18,
  },
  {
    id: 'MATIC',
    name: 'Matic Token (Ethereum)',
    type: 'ERC20',
    contractAddress: '0x7D1AfA7B718fb893dB30A3aBc0Cfc608AaCfeBB0',
    nativeAsset: 'ETH',
    decimals: 18,
  },
  {
    id: 'SOL',
    name: 'Solana',
    type: 'BASE_ASSET',
    contractAddress: '',
    nativeAsset: 'SOL',
    decimals: 9,
  },
  {
    id: 'SOL_TEST',
    name: 'Solana Test',
    type: 'BASE_ASSET',
    contractAddress: '',
    nativeAsset: 'SOL_TEST',
    decimals: 9,
  },
  {
    id: 'USDT_ERC20',
    name: 'Tether USD (Ethereum)',
    type: 'ERC20',
    contractAddress: '0xdAC17F958D2ee523a2206206994597C13D831ec7',
    nativeAsset: 'ETH',
    decimals: 6,
  },
];

export const SUPPORTED_ASSETS_LIST_TESTNET = [
  {
    id: 'AVAXTEST',
    name: 'Avalanche Fuji',
    type: 'BASE_ASSET',
    contractAddress: '',
    nativeAsset: 'AVAXTEST',
    decimals: 18,
    cmcID: 5805,
  },
  {
    id: 'BNB_TEST',
    name: 'BNB Smart Chain Testnet',
    type: 'BASE_ASSET',
    contractAddress: '',
    nativeAsset: 'BNB_TEST',
    decimals: 18,
    cmcID: 1839,
  },
  {
    id: 'BTC_TEST',
    name: 'Bitcoin Test',
    type: 'BASE_ASSET',
    contractAddress: '',
    nativeAsset: 'BTC_TEST',
    decimals: 8,
    cmcID: 1,
  },
  {
    id: 'ETH_TEST5',
    name: 'Ethereum Test (Sepolia)',
    type: 'BASE_ASSET',
    contractAddress: '',
    nativeAsset: 'ETH_TEST5',
    decimals: 18,
    cmcID: 1027,
  },
  {
    id: 'SOL_TEST',
    name: 'Solana Test',
    type: 'BASE_ASSET',
    contractAddress: '',
    nativeAsset: 'SOL_TEST',
    decimals: 9,
    cmcID: 5426,
  },
  {
    id: 'USDT_BSC_TEST',
    name: 'Tether USD (Ethereum)',
    type: 'ERC20',
    contractAddress: '0xdAC17F958D2ee523a2206206994597C13D831ec7',
    nativeAsset: 'ETH',
    decimals: 6,
    cmcID: 825,
  },
];

export const CMCTokenIDs = [1839, 1, 5426, 5805, 1027, 3890, 825];
export const CMC_TOKEN_NAMES = [
  'Avalanche',
  'BNB',
  'Bitcoin',
  'Solana',
  'Tether USDt',
  'Ethereum',
  'Polygon',
];